version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: silik-web
    ports:
      - 8002:80
    volumes: 
      - ./:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - BASE_URL=http://localhost:8002/
    networks:
      - silik
  
  mysql:
    image: mysql:latest
    container_name: silik-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silik_dev  
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - silik
      
networks:
  silik:
    driver: bridge
