<?php
defined('BASEPATH') OR exit('No direct script access allowed');

date_default_timezone_set('Asia/Makassar');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
 
$config['base_url'] = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . '/';
$config['site_name'] = $_ENV['APP_NAME'];
$config['site_description'] = $_ENV['APP_DETAIL'];

/**
 * Migration database
 */
$config['migration_enabled'] = TRUE;
$config['migration_type'] = 'sequential';
$config['migration_auto_latest'] = TRUE; 
$config['migration_path'] = APPPATH . 'migrations/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
//$config['composer_autoload'] = "vendor/autoload.php";
$config['composer_autoload'] = TRUE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/

$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = TRUE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE; 

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';


$config['rkakl_volume_satuan'] = array(
	"" => "",
	"OR" => "Orang",
	"HR" => "Hari",
	"NSK" => "Naskah",
	"KEG" => "Kegiatan",
	"KL" => "Kali",
	"JP" => "Jam Pertemuan",
	"LOK" => "Lokasi",
	"LBG" => "Lembaga",
	"KAB" => "Kabupaten",
	"KOTA" => "Kota",
	"SAT" => "Satuan",
);

$config['golongan_pangkat'] = array(
	"-" => "",
	"I/a" =>	"Juru Muda",
	"I/b" => "Juru Muda Tingkat 1",
	"I/c" => "Juru",
	"I/d" => "Juru Tingkat 1",
	"II/a" => "Pengatur Muda",
	"II/b" => "Pengatur Muda Tingkat 1",
	"II/c" => "Pengatur",
	"II/d" => "Pengatur Tingkat 1",
	"III/a" => "Penata Muda",
	"III/b" => "Penata Muda Tingkat 1",
	"III/c" => "Penata",
	"III/d" => "Penata Tingkat 1",
	"IV/a" => "Pembina",
	"IV/b" => "Pembina Tingkat 1",
	"IV/c" => "Pembina Utama Muda",
	"IV/d" => "Pembina Utama Madya",
	"IV/e" => "Pembina Utama"
);


$config['golongan_pajak'] = array(
	"" => "6",
	"-" => "5",
	"I/a" => "0",
	"I/b" => "0",
	"I/c" => "0",
	"I/d" => "0",
	"II/a" => "0",
	"II/b" => "0",
	"II/c" => "0",
	"II/d" => "0",
	"III/a" => "5",
	"III/b" => "5",
	"III/c" => "5",
	"III/d" => "5",
	"IV/a" => "15",
	"IV/b" => "15",
	"IV/c" => "15",
	"IV/d" => "15",
	"IV/e" => "15"
);

$config['paket_akun'] = array(
	"1" => array(
		"nama" => "Belanja Bahan",
		"nama_nominatif" => "Paket Belanja Bahan"
	),
	"2" => array(
		"nama" => "Belanja Jasa Profesi",
		"nama_nominatif" => "Daftar Perhitungan Pembayaran Honorarium"
	),
	"3" => array(
		"nama" => "Beban Perjalanan Dinas Biasa",
		"nama_nominatif" => "Perjalanan Dinas Biasa"
	),
	"4" => array(
		"nama" => "Beban Perjalanan Dinas Dalam Kota",
		"nama_nominatif" => "Perjalanan Dinas Dalam Kota"
	),
	"5" => array(
		"nama" => "Beban Perjalanan Dinas Paket Meeting Dalam Kota",
		"nama_nominatif" => "Perjalanan Dinas Paket Meeting Dalam Kota"
	),
	"6" => array(
		"nama" => "Belanja Barang Non Operasional Lainnya",
		"nama_nominatif" => "Barang Non Operasional Lainnya"
	),
);

$config["transport_area"] = array(
	"Badung" => "Badung",
	"Bangli" => "Bangli",
	"Buleleng" => "Buleleng",
	"Denpasar" => "Denpasar",
	"Gianyar" => "Gianyar",
	"Jembrana" => "Jembrana",
	"Karangasem" => "Karangasem",
	"Klungkung" => "Klungkung",
	"Tabanan" => "Tabanan",
	"Jakarta" => "Jakarta",
	"Lainnya" => "Lainnya"
);

$config["bank"] = array(
	"008" => "Bank Mandiri",
	"014" => "Bank BCA",
	"536" => "Bank BCA Syariah",
	"009" => "Bank BNI",
	"427" => "Bank BNI SYariah",
	"129" => "Bank BPD Bali",
	"002" => "Bank BRI",
	"422" => "Bank BRI Syariah",
	"200a" => "Bank BTN",
	"200b" => "Bank BTN Syariah",
	"213" => "Bank BTPN",
	"547" => "Bank BTPN Syariah",
	"441" => "Bank Bukopin",
	"521" => "Bank Bukopin Syariah",
	"022a" => "Bank CIMB Niaga",
	"022b" => "Bank CIMB Niaga Syariah",
	"011" => "Bank Danamon",	
	"426" => "Bank Mega",
	"506" => "Bank Mega Syariah",
	"019" => "Bank Panin",
	"013" => "Bank Permata",
	"031" => "Citibank",
	"128" => "Bank NTB Syariah",
	"451" => "Bank Syariah Indonesia",
	"110" => "Bank Jabar",
    "111" => "Bank DKI",
    "112" => "Bank BPD DIY",
    "113" => "Bank Jateng",
    "114" => "Bank Jatim",
    "115" => "Bank Jambi",
    "116" => "Bank Aceh",
    "117" => "Bank Sumut",
    "118" => "Bank Nagari",
    "119" => "Bank Riau",
    "120" => "Bank Sumsel Babel",
    "121" => "Bank Lampung",
    "122" => "Bank Kalsel",
    "123" => "Bank Kalbar",
    "124" => "Bank Kaltim",
    "125" => "Bank Kalteng",
    "126" => "Bank Sulselbar",
    "127" => "Bank SulutGo",
    "128" => "Bank NTB",
    "130" => "Bank NTT",
    "131" => "Bank Maluku",
    "132" => "Bank Papua",
    "133" => "Bank Bengkulu",
    "134" => "Bank Sulteng",
    "135" => "Bank Sultra",
    "137" => "Bank Banten"
);

$config["kode_bank"] = array(
	"Bank Mandiri" => array(
		"alias" => "Mandiri", 
		"kode" => "0080017"
	),
	"Bank BCA" => array(
		"alias" => "BCA", 
		"kode" => "0140397"
	),
	"Bank BCA Syariah" => array(
		"alias" => "BCA SYARIAH", 
		"kode" => "5360017"
	),
	"Bank BNI" => array(
		"alias" => "BNI", 
		"kode" => "0090010"
	),
	"Bank BNI SYariah" => array(
		"alias" => "BNI SYARIAH", 
		"kode" => "4270027"
	),
	"Bank BPD Bali" => array(
		"alias" => "BPD BALI", 
		"kode" => "1290013"
	),
	"Bank BRI" => array(
		"alias" => "BRI", 
		"kode" => "0020307"
	),
	"Bank BRI Syariah" => array(
		"alias" => "BRI SYARIAH", 
		"kode" => "4220051"
	),
	"Bank BTN" => array(
		"alias" => "BTN", 
		"kode" => "2000150"
	),
	"Bank BTN Syariah" => array(
		"alias" => "BTN Syariah", 
		"kode" => "2009928"
	),
	"Bank BTPN" => array(
		"alias" => "BTPN", 
		"kode" => "2130101"
	),
	"Bank BTPN Syariah" => array(
		"alias" => "BTPN SYARIAH", 
		"kode" => "5470046"
	),
	"Bank Bukopin" => array(
		"alias" => "BUKOPIN", 
		"kode" => "4410010"
	),
	"Bank Bukopin Syariah" => array(
		"alias" => "BUKOPIN SYARIAH", 
		"kode" => "5210031"
	),
	"Bank CIMB Niaga" => array(
		"alias" => "BANK CIMB", 
		"kode" => "0220026"
	),
	"Bank CIMB Niaga Syariah" => array(
		"alias" => "CIMB NIAGA UNIT USAHA SYARIAH", 
		"kode" => "0229920"
	),
	"Bank Danamon" => array(
		"alias" => "DANAMON", 
		"kode" => "0110042"
	),
	"Bank Danamon Syariah" => array(
		"alias" => "DANAMON UNIT SYARIAH", 
		"kode" => "0119920"
	),
	"Bank Mega" => array(
		"alias" => "BANK MEGA", 
		"kode" => "4260121"
	),
	"Bank Mega Syariah" => array(
		"alias" => "MEGA SYARIAH", 
		"kode" => "5060016"
	),
	"Bank Panin" => array(
		"alias" => "PANIN BANK", 
		"kode" => "0190017"
	),
	"Bank Permata" => array(
		"alias" => "BANK PERMATA", 
		"kode" => "0130475"
	),
	"Citibank" => array(
		"alias" => "CITIBANK", 
		"kode" => "0310305"
	),
	"Bank NTB Syariah" => array(
		"alias" => "BANK NTB", 
		"kode" => "1280010"
	),
	"Bank Syariah Indonesia" => array(
		"alias" => "BANK SYARIAH INDONESIA", 
		"kode" => "4510017"
	),
	"Bank Jabar" => array(
		"alias" => "BANK JABAR", 
		"kode" => "1100323"
	),
	"Bank DKI" => array(
		"alias" => "BANK DKI", 
		"kode" => "1110012"
	),
	"Bank BPD DIY" => array(
		"alias" => "BANK BPD DIY", 
		"kode" => "1120015"
	),
	"Bank Jateng" => array(
		"alias" => "BANK JATENG", 
		"kode" => "1130348"
	),
	"Bank Jatim" => array(
		"alias" => "BANK JATIM", 
		"kode" => "1140383"
	),
	"Bank Jambi" => array(
		"alias" => "BANK JAMBI", 
		"kode" => "1150014"
	),
	"Bank Aceh" => array(
		"alias" => "BANK ACEH", 
		"kode" => "1160017"
	),
	"Bank Sumut" => array(
		"alias" => "BANK SUMUT", 
		"kode" => "1170010"
	),
	"Bank Nagari" => array(
		"alias" => "BANK NAGARI", 
		"kode" => "1180013"
	),
	"Bank Riau" => array(
		"alias" => "BANK RIAU", 
		"kode" => "1190016"
	),
	"Bank Sumsel Babel" => array(
		"alias" => "BANK SUMSEL BABEL", 
		"kode" => "1200016"
	),
	"Bank Lampung" => array(
		"alias" => "BANK LAMPUNG", 
		"kode" => "1210051"
	),
	"Bank Kalsel" => array(
		"alias" => "BANK KALSEL", 
		"kode" => "1220012"
	),
	"Bank Kalbar" => array(
		"alias" => "BANK KALBAR", 
		"kode" => "1230015"
	),
	"Bank Kaltim" => array(
		"alias" => "BANK KALTIM", 
		"kode" => "1240018"
	),
	"Bank Kalteng" => array(
		"alias" => "BANK KALTENG", 
		"kode" => "1250011"
	),
	"Bank Sulselbar" => array(
		"alias" => "BANK SULSELBAR", 
		"kode" => "1260027"
	),
	"Bank SulutGo" => array(
		"alias" => "BANK SULUTGO", 
		"kode" => "1270017"
	),
	"Bank NTB" => array(
		"alias" => "BANK NTB", 
		"kode" => "1280010"
	),
	"Bank NTT" => array(
		"alias" => "BANK NTT", 
		"kode" => "1300013"
	),
	"Bank Maluku" => array(
		"alias" => "BANK MALUKU", 
		"kode" => "1310016"
	),
	"Bank Papua" => array(
		"alias" => "BANK PAPUA", 
		"kode" => "1320019"
	),
	"Bank Bengkulu" => array(
		"alias" => "BANK BENGKULU", 
		"kode" => "1330012"
	),
	"Bank Sulteng" => array(
		"alias" => "BANK SULTENG", 
		"kode" => "1340015"
	),
	"Bank Sultra" => array(
		"alias" => "BANK SULTRA", 
		"kode" => "1350018"
	),
	"Bank Banten" => array(
		"alias" => "BANK BANTEN", 
		"kode" => "1370017"
	)
);

$config["user_akses"] = array(
	"kegiatan" => array(
		"list" => array(
			"value" => 1,
			"name" => "List Kegiatan"
		),
		"add" => array(
			"value" => 1,
			"name" => "Add Kegiatan"
		),
		"edit" => array(
			"value" => 1,
			"name" => "Edit Kegiatan"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete Kegiatan"
		),
		"duplikat" => array(
			"value" => 1,
			"name" => "Duplikat Kegiatan"
		)
	),
	"kegiatan_item" => array(
		"list" => array(
			"value" => 1,
			"name" => "List Item"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add Item"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit Item"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete Item"
		),
	),
	
	"data_dukung_kegiatan" => array(
		"list" => array(
			"value" => 1,
			"name" => "List Data Dukung"
		),
		"add" => array(
			"value" => 1,
			"name" => "Add Data Dukung"
		),
	),
	/*"hai_bgp" => array(
		"list" => array(
			"value" => 1,
			"name" => "List Hai BGP"
		)
	),*/
	"keuangan" => array(
		"apr_perjadin" => array(
			"value" => 0,
			"name" => "Approve Laporan Perjadin"
		),
		"scan_perjadin" => array(
			"value" => 0,
			"name" => "Scan Laporan Perjadin"
		),
	),
	"spj" => array(
		"list" => array(
			"value" => 0,
			"name" => "List SPJ"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add SPJ"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit SPJ"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete SPJ"
		),
		"pembayaran" => array(
			"value" => 0,
			"name" => "Payment"
		)
	),
	"spj_kegiatan" => array(
		"list" => array(
			"value" => 0,
			"name" => "List SPJ Kegiatan"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add SPJ Kegiatan"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit SPJ Kegiatan"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete SPJ Kegiatan"
		),
		"pembayaran" => array(
			"value" => 0,
			"name" => "Payment"
		)
	),
	"kepegawaian" => array(
		"penugasan" => array(
			"value" => 0,
			"name" => "Penugasan"
		),
		"penugasan_dalam_kota" => array(
			"value" => 0,
			"name" => "Penugasan Dalam Kota"
		),
		"apr_penugasan" => array(
			"value" => 0,
			"name" => "Approve Penugasan"
		),
	),
	"pengaturan" => array(
		"satker" => array(
			"value" => 0,
			"name" => "Satker"
		),
		"api" => array(
			"value" => 0,
			"name" => "API"
		),
		"pejabat" => array(
			"value" => 0,
			"name" => "Pejabat"
		),
		"mail" => array(
			"value" => 0,
			"name" => "Mail"
		)
	),
	"template" => array(
		"sertifikat" => array(
			"value" => 0,
			"name" => "Sertifikat"
		)
	),
	"user" => array(
		"list" => array(
			"value" => 0,
			"name" => "List User"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add User"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit User"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete User"
		),
		"reset_password" => array(
			"value" => 0,
			"name" => "Reset Pasword User"
		),
		"access" => array(
			"value" => 0,
			"name" => "Set Access User"
		)
	),
	"biodata" => array(
		"list" => array(
			"value" => 0,
			"name" => "List Biodata"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add Biodata"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit Biodata"
		),
		"delete" => array(
			"value" => 0,
			"name" => "Delete Biodata"
		),
		"import_data_bank" => array(
			"value" => 0,
			"name" => "Import Data Bank"
		)
	),
	"komponen_kegiatan" => array(
		"list" => array(
			"value" => 0,
			"name" => "List Komponen Kegiatan"
		),
		"add" => array(
			"value" => 0,
			"name" => "Add Komponen Kegiatan"
		),
		"edit" => array(
			"value" => 0,
			"name" => "Edit Komponen Kegiatan"
		), 
	),
	"laporan" => array(
		"list_penugasan" => array(
			"value" => 0,
			"name" => "List Laporan Penugasan"
		)
	)
);

$config["sertifikat_fonts"] = array(
	"adinekirnberg" => array(1, "adinekirnberg.ttf"),
	"affectionatelyyours" => array(1, "affectionatelyyours.ttf"),
	"akadora" => array(1, "akadora.ttf"),
	"alexbrush" => array(1, "alexbrush.ttf"),
	"allema" => array(1, "allema.ttf"),
	"arabella" => array(1, "arabella.ttf"),
	"arial" => array(0, ""),
	"aspire" => array(1, "aspire.ttf"),
	"autobus" => array(1, "autobus.ttf"),
	"cambria" => array(1, "cambria.ttf"),
	"geraldine" => array(1, "geraldine.ttf"),
	"germaniaone" => array(1, "germaniaone.ttf"),
	"greatvibes" => array(1, "greatvibes.ttf"),
	"honey_script" => array(1, "honey_script.ttf"),
	"little_sunshine" => array(1, "little_sunshine.ttf"),
	"times new roman" => array(0, "")
);

$config["unsur_satuan"] = array(
	"KB" => array("kb","kelompok bermain"),
	"PAUD" => array("paud"),
	"TK" => array("tk"," tk"),
	"SD" => array("sd", "satuan pendidikan sd", "satdik sd", "uptd sd"),
	"SMP" => array("smp"),
	"SMA" => array("sma","smk"),
	"SLB" => array("slb"),
	"PKBM" => array("pkbm", "denpasar institute"),
	"SPNF SKB" => array("spnf skb", "skb", "sp skb","spnf-skb","uptd skb","uptd spnf skb"),
	"Universitas/Perguruan Tinggi" => array("fakultas", "universitas", "perguruan tinggi", "institut", "sekolah tinggi", "stkip agama hindu", "politeknik ganesha guru", "stah negeri mpu kuturan"),
	"Dinas Pendidikan" => array("disdik", "dinas pendidikan", "upt disdikpora", "korwil dinas pendidikan", "upt dissikpora", "dinas dikpora", "dinas dokpora", "upt.disdikpora", "upt disdipora"),
	$_ENV['BGP_CONFIG_3'] => array($_ENV['BGP_CONFIG_1'], $_ENV['BGP_CONFIG_2'], $_ENV['BGP_CONFIG_3']),
	"BGP BBGP" => array("bgp", "bbgp", "balai guru penggerak", "balai besar guru penggerak"),
	"BPMP BBPMP" => array("bpmp", "bbpmp", "balai penjaminan mutu pendidikan", "balai besar penjaminan mutu pendidikan"),
	"Kemenag" => array("kemenag", "kementerian agama", "krmenterian agama")
);

// Automatic Year
$yearNow = date("Y");

foreach (range(2022, $yearNow) as $confYear) {
	$config["tahun_anggaran"][] = $confYear;
}

// TABLE MASTER & TRANSACTION
$config["db_master_table"] = array(
	"biodata",
	"kutipan",
	"master_komponen_kegiatan",
	"migrations",
	"pengaturan",
	"sertifikat",
	"user",
	"user_document"
);
