<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config["provinsi"] = array(
	'Aceh' => array(
			'Aceh Barat',
			'Aceh Barat Daya',
			'Aceh Besar',
			'Aceh Jaya',
			'Aceh Selatan',
			'Aceh Singkil',
			'Aceh Tamiang',
			'Aceh Tengah',
			'Aceh Tenggara',
			'Aceh Timur',
			'Aceh Utara',
			'Bener Meriah',
			'Bireuen',
			'Gayo Lues',
			'Nagan Raya',
			'Pidie',
			'Pidie Jaya',
			'Simeulue',
			'Banda Aceh',
			'Langsa',
			'Lhokseumawe',
			'Sabang',
			'Subulussalam',
			),
	'Bali' => array(
			'Badung',
			'Bangli',
			'Buleleng',
			'Gianyar',
			'Jembrana',
			'Karangasem',
			'Klungkung',
			'Tabanan',
			'Denpasar',
			),
	'Banten' => array(
			'Lebak',
			'Pandeglang',
			'Serang',
			'Tangerang',
			'Cilegon',
			'Kota Serang',
			'Kota Tangerang',
			'Tangerang selatan',
			),
	'Bengkulu' => array(
			'Bengkulu Selatan',
			'Bengkulu Tengah',
			'Bengkulu Utara',
			'Kaur',
			'Kapahiang',
			'Lebong',
			'Mukomuko',
			'Rejang Lebong',
			'Seluma',
			'Bengkulu',
			),
	'D.I Yogyakarta' => array(
			'Bantul',
			'Gunung Kidul',
			'Kulon Progo',
			'Sleman',
			'Yogyakarta',
			),
	'D.K.I Jakarta' => array(
			'Kepulauan Seribu',
			'Jakarta Barat',
			'Jakarta Pusat',
			'Jakarta Selatan',
			'Jakarta Timur',
			'Jakarta Utara',
			),
	'Gorontalo' => array(
			'Boalemo',
			'Bone Bolango',
			'Gorontalo',
			'Gorontalo Utara',
			'Pahuwato',
			'Gorontalo',
			),
	'Jambi' => array(
			'Batanghari',
			'Bungo',
			'Kerinci',
			'Merangin',
			'Muaro Jambi',
			'Sarolangun',
			'Tanjung Jabung Barat',
			'Tanjung Jabung Timur',
			'Tebo',
			'Jambi',
			'Sungai Penuh',
			),
	'Jawa Barat' => array(
			'Bandung',
			'Bandung Barat',
			'Bekasi',
			'Bogor',
			'Ciamis',
			'Cianjur',
			'Cirebon',
			'Garut',
			'Indramayu',
			'Karawang',
			'Kuningan',
			'Majalengka',
			'Pangandaran',
			'Purwakarta',
			'Subang',
			'Sukabumi',
			'Sumedang',
			'Tasikmalaya',
			'Bandung',
			'Banjar',
			'Bekasi',
			'Bogor',
			'Cimahi',
			'Cirebon',
			'Depok',
			'Sukabumi',
			'Kota Tasikmalaya',
			),
	'Jawa Tengah' => array(
			'Banjarnegara',
			'Banyumas',
			'Batang',
			'Blora',
			'Boyolali',
			'Brebes',
			'Cilacap',
			'Demak',
			'Grobogan',
			'Jepara',
			'Karanganyar',
			'Kebumen',
			'Kendal',
			'Klaten',
			'Kudus',
			'Magelang',
			'Pati',
			'Pekalongan',
			'Pemalang',
			'Purbalingga',
			'Purworejo',
			'Rembang',
			'Semarang',
			'Sragen',
			'Sukoharjo',
			'Tegal',
			'Temanggung',
			'Wonogiri',
			'Wonosobo',
			'Magelang',
			'Pekalongan',
			'Salatiga',
			'Semarang',
			'Surakarta',
			'Tegal',
			),
	'Jawa Timur' => array(
			'Bangkalan',
			'Banyuwangi',
			'Blitar',
			'Bojonegoro',
			'Bondowoso',
			'Gresik',
			'Jember',
			'Jombang',
			'Kediri',
			'Lamongan',
			'Lumajang',
			'Madiun',
			'Magetan',
			'Malang',
			'Mojokerto',
			'Nganjuk',
			'Ngawi',
			'Pacitan',
			'Pamekasan',
			'Pasuruan',
			'Ponorogo',
			'Probolinggo',
			'Sampang',
			'Sidoarjo',
			'Situbondo',
			'Sumenep',
			'Trenggalek',
			'Tuban',
			'Tulungagung',
			'Batu',
			'Blitar',
			'Kediri',
			'Madiun',
			'Malang',
			'Mojokerto',
			'Pasuruan',
			'Probolinggo',
			'Surabaya',
			),
	'Kalimantan Barat' => array(
			'Bengkayang',
			'Kapuas Hulu',
			'Kayong Utara',
			'Ketapang',
			'Kubu Raya',
			'Landak',
			'Melawi',
			'Pontianak',
			'Sambas',
			'Sanggau',
			'Sekadau',
			'Sintang',
			'Pontianak',
			'Singkawang',
			),
	'Kalimantan Selatan' => array(
			'Balangan',
			'Banjar',
			'Barito Kuala',
			'Hulu Sungai Selatan',
			'Hulu Sungai Tengah',
			'Hulu Sungai Utara',
			'Kotabaru',
			'Tabalong',
			'Tanah Bumbu',
			'Tanah Laut',
			'Tapin',
			'Banjarbaru',
			'Banjarmasin',
			),
	'Kalimantan Tengah' => array(
			'Barito Selatan',
			'Barito Timur',
			'Barito Utara',
			'Gunung Mas',
			'Kapuas',
			'Katingan',
			'Kotawaringin Barat',
			'Kotawaringin Timur',
			'Lamandau',
			'Murung Raya',
			'Pulang Pisau',
			'Sukamara',
			'Seruyan',
			'Palangka Raya',
			),
	'Kalimantan Timur' => array(
			'Berau',
			'Kutai Barat',
			'Kutai Kartanegara',
			'Kutai Timur',
			'Paser',
			'Penajam Paser Utara',
			'Mahakam Ulu',
			'Balikpapan',
			'Bontang',
			'Samarinda',
			),
	'Kalimantan Utara' => array(
			'Bulungan',
			'Malinau',
			'Nunukan',
			'Tana Tidung',
			'Tarakan',
			),
	'Kepulauan Bangka Belitung' => array(
			'Bangka',
			'Bangka Barat',
			'Bangka Selatan',
			'Bangka Tengah',
			'Belitung',
			'Belitung Timur',
			'Pangkal Pinang',
			),
	'Kepulauan Riau' => array(
			'Bintan',
			'Karimun',
			'Kepulauan Anambas',
			'Lingga',
			'Natuna',
			'Batam',
			'Tanjung Pinang',
			),
	'Lampung' => array(
			'Lampung Barat',
			'Lampung Selatan',
			'Lampung Tengah',
			'Lampung Timur',
			'Lampung Utara',
			'Mesuji',
			'Pesawaran',
			'Pringsewu',
			'Tanggamus',
			'Tulang Bawang',
			'Tulang Bawang Barat',
			'Way Kanan',
			'Pesisir Barat',
			'Bandar Lampung',
			'Kotabumi',
			'Liwa',
			'Metro',
			),
	'Maluku' => array(
			'Buru',
			'Buru Selatan',
			'Kepulauan Aru',
			'Maluku Barat Daya',
			'Maluku Tengah',
			'Maluku Tenggara',
			'Maluku Tenggara Barat',
			'Seram Bagian Barat',
			'Seram Bagian Timur',
			'Ambon',
			'Tual',
			),
	'Maluku Utara' => array(
			'Halmahera Barat',
			'Halmahera Tengah',
			'Halmahera Utara',
			'Halmahera Selatan',
			'Halmahera Timur',
			'Kepulauan Sula',
			'Pulau Morotai',
			'Pulau Taliabu',
			'Ternate',
			'Tidore Kepulauan',
			),
	'Nusa Tenggara Barat' => array(
			'Bima',
			'Dompu',
			'Lombok Barat',
			'Lombok Tengah',
			'Lombok Timur',
			'Lombok Utara',
			'Sumbawa',
			'Sumbawa Barat',
			'Bima',
			'Mataram',
			),
	'Nusa Tenggara Timur' => array(
			'Alor',
			'Belu',
			'Ende',
			'Flores Timur',
			'Kupang',
			'Lembata',
			'Manggarai',
			'Manggarai Barat',
			'Manggarai Timur',
			'Ngada',
			'Nagekeo',
			'Rote Ndao',
			'Sabu Raijua',
			'Sikka',
			'Sumba Barat',
			'Sumba Barat Daya',
			'Sumba Tengah',
			'Sumba Timur',
			'Timor Tengah Selatan',
			'Timor Tengah Utara',
			'Kupang',
			),
	'Papua' => array(
			'Asmat',
			'Biak Numfor',
			'Boven Digoel',
			'Deiyai',
			'Dogiyai',
			'Intan Jaya',
			'Jayapura',
			'Jayawijaya',
			'Keerom',
			'Kepulauan Yapen',
			'Lanny Jaya',
			'Mamberamo Raya',
			'Mamberamo Tengah',
			'Mappi',
			'Merauke',
			'Mimika',
			'Nabire',
			'Nduga',
			'Paniai',
			'Pegunungan Bintang',
			'Puncak',
			'Puncak Jaya',
			'Sarmi',
			'Supiori',
			'Tolikara',
			'Waropen',
			'Yahukimo',
			'Yalimo',
			'Jayapura',
			),
	'Papua Barat' => array(
			'Fakfak',
			'Kaimana',
			'Manokwari',
			'Manokwari Selatan',
			'Maybrat',
			'Pegunungan Arfak',
			'Raja Ampat',
			'Sorong',
			'Sorong Selatan',
			'Tambrauw',
			'Teluk Bintuni',
			'Teluk Wondama',
			'Sorong',
			),
	'Riau' => array(
			'Bengkalis',
			'Indragiri Hilir',
			'Indragiri Hulu',
			'Kampar',
			'Kuantan Singingi',
			'Pelalawan',
			'Rokan Hilir',
			'Rokan Hulu',
			'Siak',
			'Kepulauan Meranti',
			'Dumai',
			'Pekanbaru',
			),
	'Sulawesi Barat' => array(
			'Majene',
			'Mamasa',
			'Mamuju',
			'Mamuju Utara',
			'Polewali Mandar',
			'Mamuju Tengah',
			),
	'Sulawesi Selatan' => array(
			'Bantaeng',
			'Barru',
			'Bone	Watampone',
			'Bulukumba',
			'Enrekang',
			'Gowa',
			'Jeneponto',
			'Kepulauan Selayar',
			'Luwu',
			'Luwu Timur',
			'Luwu Utara',
			'Maros',
			'Pangkajene dan Kepulauan',
			'Pinrang',
			'Sidenreng Rappang',
			'Sinjai',
			'Soppeng',
			'Takalar',
			'Tana Toraja',
			'Toraja Utara',
			'Wajo',
			'Makassar',
			'Palopo',
			'Parepare',
			),
	'Sulawesi Tengah' => array(
			'Banggai',
			'Banggai Kepulauan',
			'Banggai Laut',
			'Buol',
			'Donggala',
			'Morowali',
			'Parigi Moutong',
			'Poso',
			'Sigi',
			'Tojo Una-Una',
			'Tolitoli',
			'Palu',
			),
	'Sulawesi Tenggara' => array(
			'Bombana',
			'Buton',
			'Buton Utara',
			'Kolaka',
			'Kolaka Timur',
			'Kolaka Utara',
			'Konawe',
			'Konawe Selatan',
			'Konawe Utara',
			'Konawe Kepulauan',
			'Muna',
			'Wakatobi',
			'Bau-Bau',
			'Kendari',
			),
	'Sulawesi Utara' => array(
			'Bolaang Mongondow',
			'Bolaang Mongondow Selatan',
			'Bolaang Mongondow Timur',
			'Bolaang Mongondow Utara',
			'Kepulauan Sangihe',
			'Kepulauan Siau Tagulandang Biaro',
			'Kepulauan Talaud',
			'Minahasa',
			'Minahasa Selatan',
			'Minahasa Tenggara',
			'Minahasa Utara',
			'Bitung',
			'Kotamobagu',
			'Manado',
			'Tomohon',
			),
	'Sumatera Barat' => array(
			'Agam',
			'Dharmasraya',
			'Kepulauan Mentawai',
			'Lima Puluh Kota',
			'Padang Pariaman',
			'Pasaman',
			'Pasaman Barat',
			'Pesisir Selatan',
			'Sijunjung',
			'Solok',
			'Solok Selatan',
			'Tanah Datar',
			'Bukittinggi',
			'Padang',
			'Padangpanjang',
			'Pariaman',
			'Payakumbuh',
			'Sawahlunto',
			'Solok',
			),
	'Sumatera Selatan' => array(
			'Banyuasin',
			'Empat Lawang',
			'Lahat',
			'Muara Enim',
			'Musi Banyuasin',
			'Musi Rawas',
			'Ogan Ilir',
			'Ogan Komering Ilir',
			'Ogan Komering Ulu',
			'Ogan Komering Ulu Selatan',
			'Penukal Abab Lematang Ilir',
			'Ogan Komering Ulu Timur',
			'Lubuklinggau',
			'Pagar Alam',
			'Palembang',
			'Prabumulih',
			),
	'Sumatera Utara' => array(
			'Asahan',
			'Batubara',
			'Dairi',
			'Deli Serdang',
			'Humbang Hasundutan',
			'Karo	Kabanjahe',
			'Labuhanbatu',
			'Labuhanbatu Selatan',
			'Labuhanbatu Utara',
			'Langkat',
			'Mandailing Natal',
			'Nias',
			'Nias Barat',
			'Nias Selatan',
			'Nias Utara',
			'Padang Lawas',
			'Padang Lawas Utara',
			'Pakpak Bharat',
			'Samosir',
			'Serdang Bedagai',
			'Simalungun',
			'Tapanuli Selatan',
			'Tapanuli Tengah',
			'Tapanuli Utara',
			'Toba Samosir',
			'Binjai',
			'Gunungsitoli',
			'Medan',
			'Padangsidempuan',
			'Pematangsiantar',
			'Sibolga',
			'Tanjungbalai',
			'Tebing Tinggi',
			),
	);